### ISSUE TITLE
Unstable behavior using @CircuitBreaker and @Retry

### ISSUE THREAD

**Issue by NicoNes** [smallrye/smallrye-fault-tolerance#456]
Hi guys,

Let's consider following resource method:

```
@GET
@Retry(delay = 5, maxRetries = 4, delayUnit = ChronoUnit.SECONDS, jitter = 0, maxDuration = 0, abortOn = CircuitBreakerOpenException.class)
@CircuitBreaker(requestVolumeThreshold = 2, failureRatio = 0.5)
public Response test() throws Exception {
	System.out.println("test invoked");
	throw new Exception();
}
```

When invoking this resource, I was expected the following output:

```
test invoked
test invoked
 [qtp1212116343-16] WARN  org.eclipse.jetty.servlet.ServletHandler - /HelloWorldSample/HelloWorldApplication/EchoResource
org.jboss.resteasy.spi.UnhandledException: org.eclipse.microprofile.faulttolerance.exceptions.CircuitBreakerOpenException:
```

but instead I get :

```
test invoked
test invoked
test invoked
test invoked
test invoked
14:08:07.382 [qtp1212116343-16] WARN  org.eclipse.jetty.servlet.ServletHandler - /HelloWorldSample/HelloWorldApplication/EchoResource
org.jboss.resteasy.spi.UnhandledException: java.lang.Exception
```

or sometimes

```
test invoked
test invoked
test invoked
14:13:11.015 [qtp1212116343-16] WARN  org.eclipse.jetty.servlet.ServletHandler - /HelloWorldSample/HelloWorldApplication/EchoResource
org.jboss.resteasy.spi.UnhandledException: org.eclipse.microprofile.faulttolerance.exceptions.CircuitBreakerOpenException:
```

It looks like a concurrency issue or am I missing something ?

Thanks

**Comment by Ladicek** [comment]
Hi,

concurrency issue is always a possibility :-), but first, we should get your expectations straight.

You didn't configure a circuit breaker delay (which is the delay after which an open circuit breaker moves to half-open), so it defaults to 5 seconds. Your retry delay (which is the delay between retry attempts) is also 5 seconds. It should be obvious that the timer has certain precision, so those 5 seconds between retries could easily be say 4995 millis (in which case the circuit breaker is still open and will throw), or it could be 5005 millis (in which case the circuit breaker is half-open and will allow 1 probe invocation to proceed).

If you set the circuit breaker delay or the retry delay to some other value, so that there's a significant difference, the behavior should become stable. (But note that circuit breaker is stateful. If you invoke the method from multiple threads at the same time, each thread will have its own retry, but they will all share the same circuit breaker.)

Does that help?

**Comment by NicoNes** [comment]
Hi @Ladicek,

Thanks for your answer and analysis. You're rirght, I did not pay attention to the circuit breaker delay default value of 5 seconds.
It makes sense.

Thanks !

**Comment by Ladicek** [comment]
Glad it helps!
