### ISSUE TITLE
Modest proposal: Google Error Prone Maven plugin

### ISSUE THREAD

**Issue by magicprinc** [smallrye/smallrye-fault-tolerance#911]
https://errorprone.info/
https://errorprone.info/docs/installation

It gives quite a lot of false positives and generates more criticism than Mary Poppins,
but sometimes it really helps and gives interesting insides.

So maybe it's a good idea to add Google Error Prone to Maven build 🤷‍♀️

**Comment by Ladicek** [comment]
I'm a big fan of static analysis tools in princple, but in practice, they always come up with a massive amount of noise. The initial exercise of tuning the project to avoid the noise so that actual possible issues show up has always been a deterrent for me. We have Sonar set up, but as mentioned above, it is full of noise, so I just tend to rely on IntelliJ IDEA's builtin analyses when writing code.

ErrorProne in particular hooks into javac internals, which is not funny, because we run CI with multiple Java versions. That sounds like a source of troubles.
